packages:
  - "apps/*"
  - "packages/*"

onlyBuiltDependencies:
  - argon2
  - esbuild
allowBuilds:
  argon2: true
  better-sqlite3: false
  esbuild: true
patchedDependencies:
  y-prosemirror@1.3.7: patches/y-prosemirror@1.3.7.patch
